i=("Manaña habrá muchos huespedes")
print(i)
h1=(i.find("h"))
print("la primera h esta en" + " " + str(h1))
h2=(i.rfind("h"))
print("la última h esta en" + " " + str(h2))
print((i[:h1]) + (i[h2+1:]))